allow-lan: true
cfw-bypass:
- localhost
- 127.*
- 10.*
- 192.168.*
- <local>
dns:
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - dns.msftncsi.com
  - '*.ipv6.microsoft.com'
  - '*.*.xboxlive.com'
  - speedtest.cros.wr.pvp.net
  fake-ip-range: 198.18.0.1/16
  fallback:
  - tls://101.101.101.101:853
  - https://101.101.101.101/dns-query
  - https://public.dns.iij.jp/dns-query
  - https://208.67.220.220/dns-query
  fallback-filter:
    domain:
    - +.google.com
    - +.proton.me
    geoip: true
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
    - 127.0.0.1/32
  ipv6: true
  nameserver:
  - tls://223.5.5.5:853
  - https://223.6.6.6/dns-query
  - https://120.53.53.53/dns-query
external-controller: 127.0.0.1:9090
log-level: info
mode: Rule
port: 7890
proxies:
- name: "http.local"
  type: http
  server: 127.0.0.1
  port: 3128
- name: snap.linkpc.net
  server: snap.linkpc.net
  port: 8080
  type: vmess
  uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
  alterId: 0
  cipher: auto
  network: tcp
- name: oci.cbu.local
  server: oci.cbu.net
  port: 443
  type: vmess
  uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
  alterId: 0
  cipher: zero
  tls: true
  network: ws
  skip-cert-verify: false
- name: oci.publicvm.local
  server: oci.publicvm.com
  port: 443
  type: vmess
  uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
  alterId: 0
  cipher: zero
  tls: true
  network: ws
  skip-cert-verify: false
- name: hub.paotung.org
  server: hub.paotung.org
  port: 443
  type: vless
  uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
  network: tcp
  tls: true
  skip-cert-verify: false
- name: oci.cbu.net
  server: oci.cbu.net
  port: 443
  type: vless
  uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
  flow: xtls-rprx-vision
  network: tcp
  tls: true
  skip-cert-verify: false
  reality-opts:
    public-key: JGBxyfUHKZYihtDUcZHHP9nYOnE-rGulm94Fag2tsmE
  client-fingerprint: chrome
  udp: true
- name: oci.publicvm.com
  server: oci.publicvm.com
  port: 443
  type: vless
  uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
  flow: xtls-rprx-vision
  network: tcp
  tls: true
  skip-cert-verify: false
  reality-opts:
    public-key: JGBxyfUHKZYihtDUcZHHP9nYOnE-rGulm94Fag2tsmE
  client-fingerprint: chrome
  udp: true
- name: aws.donpau.com
  server: aws.donpau.com
  port: 443
  type: vmess
  uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
  alterId: 0
  cipher: auto
  network: ws
  tls: true
  skip-cert-verify: false
  ws-opts:
    path: /hubvm
- name: cfp.paotung.org
  server: cfp.paotung.org
  port: 443
  type: vmess
  uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
  alterId: 0
  cipher: auto
  network: ws
  tls: true
  skip-cert-verify: false
- name: gco.donpau.com
  server: gcc.donpau.com
  port: 443
  type: vmess
  uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
  alterId: 0
  cipher: auto
  network: ws
  tls: true
  skip-cert-verify: false
  ws-opts:
    headers:
      Host: gco.donpau.com
- name: gvm.donpau.com
  server: gvm.donpau.com
  port: 443
  type: vless
  uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
  tls: true
  skip-cert-verify: false
- name: gac.donpau.com
  server: gac.donpau.com
  port: 443
  type: vmess
  uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
  alterId: 0
  cipher: auto
  network: ws
  tls: true
- name: ggc.donpau.com
  server: gcc.donpau.com
  port: 443
  type: vmess
  uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
  alterId: 0
  cipher: auto
  network: ws
  tls: true
  skip-cert-verify: false
  ws-opts:
    headers:
      Host: ggc.donpau.com
- name: gcp.paotung.org
  server: gcp.paotung.org
  port: 443
  type: vmess
  uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
  alterId: 0
  cipher: auto
  network: ws
  tls: true
  skip-cert-verify: false
- name: gsc.donpau.com
  server: gsc.donpau.com
  port: 443
  type: vmess
  uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
  alterId: 0
  cipher: auto
  network: ws
  tls: true
  skip-cert-verify: false
- name: sdc.donpau.com
  server: sdc.donpau.com
  port: 443
  type: vmess
  uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
  alterId: 0
  cipher: auto
  network: ws
  tls: true
  skip-cert-verify: false
- dns:
  - 1.1.1.1
  - 1.0.0.1
  ip: 172.16.0.2
  mtu: 1280
  name: 🇳🇱 NL-CF-WARP-1
  port: 8886
  private-key: yHyLJCooOztm5bjtZF0XRPYemSXDmoHCJqUKDSIlEkY=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  remote-dns-resolve: true
  server: 188.114.98.208
  type: wireguard
  udp: true
- dns:
  - 1.1.1.1
  - 1.0.0.1
  ip: 172.16.0.2
  mtu: 1280
  name: 🇳🇱 NL-CF-WARP-2
  port: 3854
  private-key: yHyLJCooOztm5bjtZF0XRPYemSXDmoHCJqUKDSIlEkY=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  remote-dns-resolve: true
  server: 188.114.96.235
  type: wireguard
  udp: true
proxy-groups:
- name: 🌐 节点选择
  proxies:
  - 🇳🇱 NL-CF-WARP-1
  - hub.paotung.org
  - oci.cbu.net
  - oci.publicvm.com
  - aws.donpau.com
  - cfp.paotung.org
  - gco.donpau.com
  - gvm.donpau.com
  - gac.donpau.com
  - ggc.donpau.com
  - gcp.paotung.org
  - gsc.donpau.com
  type: select
rules:
- GEOIP,CN,🇳🇱 NL-CF-WARP-1
- MATCH,🇳🇱 NL-CF-WARP-1
socks-port: 7891
