allow-lan: true
cfw-bypass:
- localhost
- 127.*
- 10.*
- 192.168.*
- <local>
dns:
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - dns.msftncsi.com
  - '*.ipv6.microsoft.com'
  - '*.*.xboxlive.com'
  - speedtest.cros.wr.pvp.net
  fake-ip-range: 198.18.0.1/16
  fallback:
  - tls://101.101.101.101:853
  - https://101.101.101.101/dns-query
  - https://public.dns.iij.jp/dns-query
  - https://208.67.220.220/dns-query
  fallback-filter:
    domain:
    - +.google.com

    - +.proton.me
    geoip: true
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
    - 127.0.0.1/32
  ipv6: true
  nameserver:
  - tls://223.5.5.5:853
  - https://223.6.6.6/dns-query
  - https://120.53.53.53/dns-query
external-controller: 127.0.0.1:9090
log-level: info
mode: Rule
port: 7890
proxies:
- dns:
  - 1.1.1.1
  - 1.0.0.1
  ip: 172.16.0.2
  mtu: 1280
  name: 🇳🇱 NL-CF-WARP-1
  port: 8886
  private-key: yHyLJCooOztm5bjtZF0XRPYemSXDmoHCJqUKDSIlEkY=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  remote-dns-resolve: true
  server: 188.114.98.208
  type: wireguard
  udp: true
- dns:
  - 1.1.1.1
  - 1.0.0.1
  ip: 172.16.0.2
  mtu: 1280
  name: 🇳🇱 NL-CF-WARP-2
  port: 3854
  private-key: yHyLJCooOztm5bjtZF0XRPYemSXDmoHCJqUKDSIlEkY=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  remote-dns-resolve: true
  server: 188.114.96.235
  type: wireguard
  udp: true
proxy-groups:
- name: 🌐 节点选择
  proxies:
  - 💡 自动选择
  - 🇳🇱 NL-CF-WARP-1
  type: select
rules:
- GEOIP,CN,👉 国内网站
- MATCH,👉 例外网站
socks-port: 7891
