################################## 
###  Creator:baopad@yahoo.com  ###
##################################
#external-controller: 127.0.0.1:9090
#port: 7891
#socks-port: 7892
mixed-port: 7890
mode: Rule
log-level: silent
tcp-concurrent: true
#ipv6: false
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 114.114.114.114
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
    - https://1.12.12.12/dns-query
    #- https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query
    #- https://223.6.6.6/dns-query
  fallback:
    - https://dns.paotung.org/dns-query
    - https://hub.paotung.org/dns-query
    - https://gvm.donpau.com/dns-query
    - tls://dns.umbrella.com
    #- https://doh.sb/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
proxies:
  - name: Cloudflare Warp+
    server: 162.159.192.134
    port: 988
    type: wireguard
    ip: 172.16.0.2
    mtu: 1280
    private-key: QEJ749VOpkKK/VRhrEarnDcdZO+v6sTJT27sf7k2534=
    public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
    remote-dns-resolve: true    
    udp: true
  - name: snap.linkpc.net
    server: snap.linkpc.net
    port: 8080
    type: vmess
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: auto
    network: tcp
  - name: oci.cbu.local
    server: oci.cbu.net
    port: 443
    type: vmess
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: zero
    tls: true
    network: ws
    skip-cert-verify: false
  - name: oci.publicvm.local
    server: oci.publicvm.com
    port: 443
    type: vmess
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: zero
    tls: true
    network: ws
    skip-cert-verify: false
  - name: hub.paotung.org
    server: hub.paotung.org
    port: 443
    type: vless
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    network: tcp
    tls: true
    skip-cert-verify: false
  - name: oci.cbu.net
    server: oci.cbu.net
    port: 443
    type: vless
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    flow: xtls-rprx-vision
    network: tcp
    tls: true
    skip-cert-verify: false
    reality-opts:
      public-key: JGBxyfUHKZYihtDUcZHHP9nYOnE-rGulm94Fag2tsmE
    client-fingerprint: chrome
    udp: true
  - name: oci.publicvm.com
    server: oci.publicvm.com
    port: 443
    type: vless
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    flow: xtls-rprx-vision
    network: tcp
    tls: true
    skip-cert-verify: false
    reality-opts:
      public-key: JGBxyfUHKZYihtDUcZHHP9nYOnE-rGulm94Fag2tsmE
    client-fingerprint: chrome
    udp: true
  - name: aws.donpau.com
    server: aws.donpau.com
    port: 443
    type: vmess
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: auto
    network: ws
    tls: true
    skip-cert-verify: false
    ws-opts:
      path: /hubvm
  - name: cfp.paotung.org
    server: cfp.paotung.org
    port: 443
    type: vmess
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: auto
    network: ws
    tls: true
    skip-cert-verify: false
  - name: gco.donpau.com
    server: gcc.donpau.com
    port: 443
    type: vmess
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: auto
    network: ws
    tls: true
    skip-cert-verify: false
    ws-opts:
      headers:
        Host: gco.donpau.com
  - name: gvm.donpau.com
    server: gvm.donpau.com
    port: 443
    type: vless
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    tls: true
    skip-cert-verify: false
  - name: gac.donpau.com
    server: gac.donpau.com
    port: 443
    type: vmess
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: auto
    network: ws
    tls: true
  - name: ggc.donpau.com
    server: gcc.donpau.com
    port: 443
    type: vmess
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: auto
    network: ws
    tls: true
    skip-cert-verify: false
    ws-opts:
      headers:
        Host: ggc.donpau.com
  - name: gcp.paotung.org
    server: gcp.paotung.org
    port: 443
    type: vmess
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: auto
    network: ws
    tls: true
    skip-cert-verify: false
  - name: gsc.donpau.com
    server: gsc.donpau.com
    port: 443
    type: vmess
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: auto
    network: ws
    tls: true
    skip-cert-verify: false
  - name: sdc.donpau.com
    server: sdc.donpau.com
    port: 443
    type: vmess
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: auto
    network: ws
    tls: true
    skip-cert-verify: false
proxy-providers:
  provider-1:
    type: http
    url: "https://cdn.jsdelivr.net/gh/anaer/Sub@main/clash.yaml"
    interval: 3600
    path: ./profiles/a.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  provider-2:
    type: http
    url: "https://sub.maoxiongnet.com/sub?target=clash&new_name=true&url=https%3A%2F%2Fv2ray.neocities.org%2Fv2ray.txt&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online_Mini.ini"
    interval: 3600
    path: ./profiles/a.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  provider-3:
    type: http
    url: "https://git.io/emzclash"
    interval: 3600
    path: ./profiles/a.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  provider-relay1:
    type: http
    url: "https://rss.paotung.org/clash/providers/relay.yaml"
    interval: 3600
    path: ./profiles/relay1.yaml
    health-check:
      enable: true
      interval: 600
      url: "https://www.baidu.com/"
  provider-relay2:
    type: http
    url: "https://subs.zeabur.app/clash"
    interval: 3600
    path: ./profiles/relay2.yaml
    health-check:
      enable: true
      interval: 600
      url: "https://www.baidu.com/"
proxy-groups:
  - name: Provider
    type: select
    use:
      - provider-1
      - provider-2
      - provider-3
    url: https://www.gstatic.com/generate_204
    interval: 300
  - name: Relay
    type: select
    use:
      - provider-relay1
      - provider-relay2
    proxies:
      #- snap.linkpc.net
    url: "https://www.baidu.com/"
    interval: 300
  - name: Chains
    type: relay
    proxies:
      - Automatic
      - hub.paotung.org
    url: https://www.gstatic.com/generate_204
    interval: 300
  - name: Fallback
    type: fallback
    proxies:
      - hub.paotung.org
      - Automatic
    url: https://www.gstatic.com/generate_204
    interval: 300
  - name: Automatic
    type: url-test
    proxies:
      - hub.paotung.org
      - oci.cbu.net
      - oci.publicvm.com
      - aws.donpau.com
      - cfp.paotung.org
      - gco.donpau.com
      - gvm.donpau.com
      - gac.donpau.com
      - ggc.donpau.com
      - gcp.paotung.org
      - gsc.donpau.com
    url: https://www.gstatic.com/generate_204
    interval: 3600
  - name: Balance
    type: load-balance
    proxies:
      - hub.paotung.org
      - oci.publicvm.com
      - aws.donpau.com
      - cfp.paotung.org
      - gco.donpau.com
      - gsc.donpau.com
    url: https://www.gstatic.com/generate_204
    interval: 600
rules:
  - RULE-SET,consistency,hub.paotung.org
  - RULE-SET,reject,REJECT
  - RULE-SET,direct,DIRECT
  - RULE-SET,proxy,Balance
  - RULE-SET,relay,Relay
  - GEOSITE,CN,Relay
  - GEOIP,CN,Relay
  - MATCH,Balance
rule-providers:
  #Maintenance Address: https://github.com/baopad/rss/tree/main/clash/rules
  consistency:
    type: http
    behavior: classical
    url: "https://rss.paotung.org/clash/rules/consistency.yaml"
    path: ./rules/consistency.yaml
    interval: 123456
  reject:
    type: http
    behavior: classical
    url: "https://rss.paotung.org/clash/rules/reject.yaml"
    path: ./rules/reject.yaml
    interval: 123456
  direct:
    type: http
    behavior: classical
    url: "https://rss.paotung.org/clash/rules/direct.yaml"
    path: ./rules/direct.yaml
    interval: 123456
  proxy:
    type: http
    behavior: classical
    url: "https://rss.paotung.org/clash/rules/proxy.yaml"
    path: ./rules/proxy.yaml
    interval: 123456
  relay:
    type: http
    behavior: classical
    url: "https://rss.paotung.org/clash/rules/relay.yaml"
    path: ./rules/relay.yaml
    interval: 123456
