##################################
###  Creator:baopad@yahoo.com  ###
###  Subscription Address:  https://rss.paotung.org/clash/sub/config.yaml
###  Edit Address:          https://github.com/baopad/rss/edit/main/clash/sub/config.yaml
###  Direct Address:        https://github.com/baopad/rss/edit/main/clash/rules/direct.yaml
###  Reject Address:        https://github.com/baopad/rss/edit/main/clash/rules/reject.yaml
###  Proxy Address:         https://github.com/baopad/rss/edit/main/clash/rules/proxy.yaml
##################################
mixed-port: 789o
mode: Rule
log-level: silent
tcp-concurrent: true
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  #prefer-h3: true
  default-nameserver:             #解析nameserver服务器
    - 1.1.1.1
    - 8.8.8.8
    #- 114.114.114.114
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:                     #解析国(墙)内域名
    - https://dns.paotung.org/dns-query
    - https://hub.paotung.org/dns-query
    #- https://doh.pub/dns-query
    #- https://dns.alidns.com/dns-query
    #- https://1.12.12.12/dns-query
    #- https://120.53.53.53/dns-query
    #- https://223.5.5.5/dns-query
    #- https://223.6.6.6/dns-query
  fallback:                       #解析回落国(墙)外域名,通过fallback-filter规则
    - https://dns.paotung.org/dns-query
    - https://hub.paotung.org/dns-query
    #- https://ccs.linkpc.net/dns-query
    #- tls://dns.umbrella.com
    #- https://doh.sb/dns-query
  #nameserver-policy:             #指定域名解析服务器
    #'www.baidu.com': '114.114.114.114'
  proxy-server-nameserver:        #仅用于解析代理节点的域名
    - https://dns.paotung.org/dns-query
    - https://hub.paotung.org/dns-query
  fallback-filter:                #解析规则
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
      #- 0.0.0.0/32
    domain:                       #域名视为污染,fallback解析
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
proxies:
  - name: snap.linkpc.net
    server: snap.linkpc.net
    type: vmess
    port: 8080
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: auto
  - name: ccs.paotung.org
    server: ccs.paotung.org
    port: 443
    type: vmess
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: auto
    network: ws
    tls: true
    skip-cert-verify: false
  - name: oci.local
    server: oci.cbu.net
    port: 443
    type: vless
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    flow: xtls-rprx-vision
    network: tcp
    tls: true
    skip-cert-verify: false
    reality-opts:
      public-key: JGBxyfUHKZYihtDUcZHHP9nYOnE-rGulm94Fag2tsmE
    client-fingerprint: chrome
    udp: true
  - name: gce.donpau.com
    server: gcc.donpau.com
    type: vmess
    port: 443
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: auto
    servername: gce.donpau.com
    network: ws
    tls: true
    skip-cert-verify: false
    ws-opts:
      path: /vmess
      headers:
        Host: gce.donpau.com
    udp: true
  - name: ccs.linkpc.net
    server: ccs.linkpc.net
    port: 443
    type: vless
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    tls: true
    skip-cert-verify: false
  - name: cfp.paotung.org
    server: cfp.paotung.org
    type: vmess
    port: 443
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: auto
    tls: true
    network: ws
  - name: oci.cbu.net
    server: oci.cbu.net
    port: 443
    type: vmess
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: none
    tls: true
    network: ws
    ws-opts:
      path: /ccsvm
  - name: sdc.donpau.com
    server: sdc.donpau.com
    port: 443
    type: vmess
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: auto
    network: ws
    tls: true
    skip-cert-verify: false
proxy-groups:
  - name: Automatic
    type: url-test
    proxies:
      - sdc.donpau.com
      - snap.linkpc.net
    url: https://www.gstatic.com/generate_204
    interval: 600
  - name: Fallback
    type: fallback
    proxies:
      - sdc.donpau.com
      - snap.linkpc.net
    url: https://www.gstatic.com/generate_204
    interval: 300
rules:
  - RULE-SET,custom,sdc.donpau.com
  - RULE-SET,direct,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,proxy,Fallback
  #- GEOSITE,CN,DIRECT
  #- GEOIP,CN,DIRECT
  - MATCH,Fallback
rule-providers:
  #Maintenance Address: https://github.com/baopad/rss/tree/main/clash/rules
  custom:
    type: http
    behavior: classical
    url: "https://rss.paotung.org/clash/rules/custom.yaml"
    path: ./rules/custom.yaml
    interval: 123456
  direct:
    type: http
    behavior: classical
    url: "https://rss.paotung.org/clash/rules/direct.yaml"
    path: ./rules/direct.yaml
    interval: 123456
  reject:
    type: http
    behavior: classical
    url: "https://rss.paotung.org/clash/rules/reject.yaml"
    path: ./rules/reject.yaml
    interval: 123456
  proxy:
    type: http
    behavior: classical
    url: "https://rss.paotung.org/clash/rules/proxy.yaml"
    path: ./rules/proxy.yaml
    interval: 123456
