mixed-port: 7890
mode: Rule
log-level: silent
tcp-concurrent: true
proxies:
  - name: "sdc.donpau.com"
    server: sdc.donpau.com
    port: 443
    type: vmess
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: auto
    network: ws
    tls: true
    skip-cert-verify: false
  - name: "ccs.kozow.com"
    server: ccs.kozow.com
    port: 443
    type: vless
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    tls: true
    skip-cert-verify: false
  - name: "cfp.paotung.org"
    server: cfp.paotung.org
    type: vmess
    port: 443
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: auto
    tls: true
    network: ws
proxy-groups:
  - name: "Fallback"
    type: fallback
    proxies:
      - sdc.donpau.com
      - ccs.kozow.com
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
rules:
  - GEOSITE,CN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Fallback
