##############################################################################################
###  Creator:               email:baopad@yahoo.com
###  Subscription Address:  https://rss.paotung.org/clashverge/subscriptions/config.yaml
###  Edit Address:          https://github.com/baopad/rss/edit/main/clashverge/subscriptions/config.yaml
###  Custom Address:        https://github.com/baopad/rss/edit/main/clashverge/rules/custom.yaml
###  Direct Address:        https://github.com/baopad/rss/edit/main/clashverge/rules/direct.yaml
###  Proxy Address:         https://github.com/baopad/rss/edit/main/clashverge/rules/proxy.yaml
###  Reject Address:        https://github.com/baopad/rss/edit/main/clashverge/rules/reject.yaml
##############################################################################################
mixed-port: 7890
mode: Rule
log-level: silent
tcp-concurrent: true
proxies:
  - name: "oci.cbu.net"
    server: oci.cbu.net
    port: 443
    type: vless
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    flow: xtls-rprx-vision
    network: tcp
    tls: true
    skip-cert-verify: false
    reality-opts:
      public-key: JGBxyfUHKZYihtDUcZHHP9nYOnE-rGulm94Fag2tsmE
    client-fingerprint: chrome
    udp: true
  - name: "ccs.gleeze.com"
    server: gcc.donpau.com
    port: 443
    type: vmess
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: auto
    network: ws
    tls: true
    skip-cert-verify: false
    ws-opts:
      headers:
        Host: ccs.gleeze.com
  - name: "ipv6.ccs.byinter.net"
    server: ipv6.ccs.byinter.net
    type: vmess
    port: 1000
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: auto
    tls: true
    network: ws
  - name: "oci.cbu.net/ccs"
    server: oci.cbu.net
    port: 443
    type: vmess
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: auto
    network: ws
    tls: true
    skip-cert-verify: false
    ws-opts:
      path: /ccs
  - name: "ccs.byinter.net"
    server: ccs.byinter.net
    port: 443
    type: vless
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    tls: true
    skip-cert-verify: false
  - name: "ccs.paotung.org"
    server: ccs.paotung.org
    type: vmess
    port: 443
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: auto
    tls: true
    network: ws
  - name: "ccs.kozow.com"
    server: ccs.kozow.com
    port: 443
    type: vmess
    uuid: 87ae2ebc-3e45-33d9-8ed3-61a337d88888
    alterId: 0
    cipher: auto
    network: ws
    tls: true
    skip-cert-verify: false
proxy-groups:
  - name: "Automatic"
    type: url-test
    proxies:
      - ccs.kozow.com
      - ccs.byinter.net
      - ccs.paotung.org
      - oci.cbu.net/ccs
      - ccs.gleeze.com
      - ipv6.ccs.byinter.net
    url: 'https://www.gstatic.com/generate_204'
    interval: 300
  - name: "Balance"
    type: load-balance
    proxies:
      - ccs.kozow.com
      - ccs.byinter.net
      - ccs.paotung.org
      - oci.cbu.net/ccs
      - ccs.gleeze.com
      - ipv6.ccs.byinter.net
  - name: "Fallback"
    type: fallback
    proxies:
      - ccs.kozow.com
      - ccs.byinter.net
      - ccs.paotung.org
      - oci.cbu.net/ccs
      - ccs.gleeze.com
      - ipv6.ccs.byinter.net
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
rules:
  - RULE-SET,custom,Fallback
  - RULE-SET,direct,DIRECT
  - RULE-SET,proxy,Fallback
  - RULE-SET,reject,REJECT
  - GEOSITE,cn,DIRECT
  - GEOIP,cn,DIRECT
  - MATCH,Fallback
rule-providers:
  custom:
    type: http
    behavior: classical
    url: 'https://rss.paotung.org/clashverge/rules/custom.yaml'
    path: ./rules/custom.yaml
    interval: 86400
  direct:
    type: http
    behavior: classical
    url: 'https://rss.paotung.org/clashverge/rules/direct.yaml'
    path: ./rules/direct.yaml
    interval: 86400
  proxy:
    type: http
    behavior: classical
    url: 'https://rss.paotung.org/clashverge/rules/proxy.yaml'
    path: ./rules/proxy.yaml
    interval: 86400
  reject:
    type: http
    behavior: classical
    url: 'https://rss.paotung.org/clashverge/rules/reject.yaml'
    path: ./rules/reject.yaml
    interval: 86400
